# docker-compose-developpement.yaml
services:
    # nginx
    web:
        build: 
           Dockerfile: ./nginx/Dockerfile
        volumes:
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    # php
    app:
        build:
            dockerfile: ./php/Dockerfile
            target: ${BUILD_TARGET:-app}
        volumes:
            - ./app:/var/www/html
            - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
        environment:    
           
                  # See https://xdebug.org/docs/all_settings#mode
            XDEBUG_MODE: "${XDEBUG_MODE:-off}"
       

    # mysql: docker compose exec db sh -c 'mysql -uuser -p${MYSQL_PASSWORD}'
    db:  
       
        # we dont expose db ports in prod     
        ports:
            - "3306:3306"
          
        restart: unless-stopped
        

volumes:
    mysqldata:
